### ISSUE TITLE
Problem sa buildovanjem projekta

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-009-arhitektron#1]
Prilikom kompilacije (make) dobija se sledeća poruka:

```
Fatal error: can't create obj/point.o: No such file or directory
Makefile:17: recipe for target 'obj/point.o' failed
```

**Comment by NidzaKornjaca** [comment]
A da, napravite obj folder u direktorijumu projekta i probajte ponovo -
treba skockati taj Makefile jos malo :)

2017-01-01 12:41 GMT+01:00 Ivan Čukić <notifications@github.com>:

**Comment by NidzaKornjaca** [comment]
Dodat folder u strukturu projekta.
