### ISSUE TITLE
Snimak ekrana

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-009-arhitektron#3]
Napravite snimak ekrana od bar 30-ak sekundi za demonstraciju programa. Neka bude 800x600 rezolucija, format zapisa mpg.

**Comment by NidzaKornjaca** [comment]
Po specifikaciji: https://github.com/MATF-RG16/RG16-009-arhitektron/blob/master/demo_800x600.mpg
Jos jedan: https://youtu.be/VPT0OMaQgNY
